# Generated by Django 3.0.4 on 2020-03-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assignee',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
