# Generated by Django 3.0.4 on 2020-03-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assignee',
            field=models.ManyToManyField(blank=True, to='users.Person'),
        ),
    ]
