# Generated by Django 3.0.4 on 2020-03-24 21:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cases', '0002_auto_20200321_0232'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='case',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='assignee',
            field=models.ManyToManyField(blank=True, to='users.Profile', verbose_name='assignee'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='case',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(0, 'Easiest'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Hardest')], default=2, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'Lowest'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Highest')], default=2, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='case',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('finished', 'Finished')], default='new', max_length=12, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_of',
            field=models.CharField(choices=[('task', 'Task'), ('issue', 'Issue'), ('bug', 'Bug'), ('maintenance', 'Maintenance')], db_index=True, default='task', max_length=12, verbose_name='type'),
        ),
    ]
